# Generated by Django 3.1.7 on 2021-03-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210331_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='video',
        ),
    ]
