# Generated by Django 3.1.7 on 2021-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210331_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shown',
            field=models.IntegerField(default=0),
        ),
    ]
