# Generated by Django 3.1.7 on 2021-04-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
